"use strict";
exports.__esModule = true;
var message = 'Welcome back';
console.log(message);
var x = 10;
var y = 20;
var sum;
var title = 'Codevolution';
var isBeginner = true;
var total = 0;
var name = 'Latika';
var sentence = "hello ".concat(name, "\nI am learning typescript");
console.log(sentence);
